
import js from "@eslint/js";
import globals from "globals";

// A list of custom global variables used in the frontend code.
// This helps ESLint understand variables that are defined in one file (like app.js)
// and used in others without explicit imports.
const customGlobals = {
    // From globals.js and app.js
    "API_BASE_URL": "writable",
    "library": "writable",
    "currentView": "writable",
    "currentRootFolder": "writable",
    "currentPublisher": "writable",
    "currentSeries": "writable",
    "activeFilter": "writable",
    "configuredRootFolders": "writable",
    "downloadedComicIds": "writable", // Changed from readonly
    // DOM Elements
    "latestAddedButton": "readonly",
    "latestConvertedButton": "readonly",
    "downloadedButton": "readonly",
    "smartListView": "readonly",
    "smartListTitle": "readonly",
    "smartListContainer": "readonly",
    "rootFolderListDiv": "readonly",
    "rootFolderListContainer": "readonly",
    "publisherListDiv": "readonly",
    "publisherTitleH2": "readonly",
    "publisherAlphaFilter": "readonly",
    "seriesListDiv": "readonly",
    "seriesTitleH2": "readonly",
    "seriesAlphaFilter": "readonly",
    "comicListDiv": "readonly",
    "comicListTitleH2": "readonly",
    "comicAlphaFilter": "readonly",
    "searchResultsView": "readonly",
    "searchResultsTitle": "readonly",
    "searchResultsContainer": "readonly",
    "settingsModal": "readonly",
    "scanIntervalInput": "readonly",
    "apiKeyInput": "readonly",
    "settingsStatusDiv": "readonly",
    "settingsForm": "readonly",
    "scanButton": "readonly",
    "fullScanButton": "readonly",
    "logsContainer": "readonly",
    "devicesStatusDiv": "readonly",
    "devicesListDiv": "readonly",
    "refreshDevicesBtn": "readonly",
    "downloadQueueDiv": "readonly",
    "downloadsInfoDiv": "readonly",
    "latestAddedCountSpan": "readonly",
    "latestConvertedCountSpan": "readonly",
    "downloadedCountSpan": "readonly",
    // Functions from other files
    "showView": "readonly",
    "createLoadingMessage": "readonly",
    "createErrorMessage": "readonly",
    "applyDisplayInfoToComic": "readonly",
    "toggleReadStatus": "writable",
    "fetchLibrary": "writable",
    "getSeriesComics": "writable",
    "encodePath": "readonly",
    "debugLog": "writable",
    "updateFilterButtonCounts": "writable",
    "getAllDownloadedComicIds": "writable",
    "removeStaleDownloads": "writable",
    "rebuildDownloadedComics": "writable",
    "applyFilterAndRender": "writable",
    "renderDownloadedSmartList": "writable",
    "getComicStatus": "writable",
    "updateLibraryReadStatus": "writable",
    "scheduleOfflineProgressSync": "writable",
    "saveLibraryCacheToDB": "writable",
    "openOfflineDB": "writable",
    "updateDownloadedComicProgressData": "writable",
    "downloadComic": "writable",
    "showUserBadge": "writable",
    "hideAdminUI": "writable",
    "triggerScan": "writable",
    "getPageCounterTotal": "writable",
    "closeFullscreen": "writable",
    // Libraries
    "JSZip": "readonly",
    // Newly added globals from lint output
    "showRootFolderList": "writable",
    "initializeLibraryUIControls": "writable",
    "initializeViewerUIControls": "writable",
    "initializeProgressTracking": "writable",
    "loadLibraryCacheFromDB": "writable",
    "applyDisplayInfoToLibrary": "writable",
    "estimateLibrarySize": "writable",
    "rebuildLatestComics": "writable",
    "rebuildLatestConvertedComics": "writable",
    "mergeOfflineStatusesIntoLibrary": "writable",
    "backgroundSyncOperations": "writable",
    "ctApplyBtn": "writable",
    "ctSkipBtn": "writable",
    "ctOutputDiv": "writable",
    "openCTModal": "writable",
    "ctModal": "writable",
    "ctEventSource": "writable",
    "ctAwaitingMatches": "writable",
    "closeCTModal": "writable",
    "ctConfirmBar": "writable",
    "ctConfirmMessage": "writable",
    "ctConfirmYes": "writable",
    "handleCtConfirmYes": "writable",
    "ctMatchBody": "writable",
    "saveCtSettings": "writable",
    "showCtConfirm": "writable",
    "handleCtConfirmNo": "writable",
    "ctButton": "writable",
    "ctScheduleInput": "writable",
    "ctClearOutputBtn": "writable",
    "ctRunBtn": "writable",
    "ctTabSettings": "writable",
    "ctTabOutput": "writable",
    "ctContentSettings": "writable",
    "ctContentOutput": "writable",
    "searchStatusDiv": "writable",
    "searchResultsUl": "writable",
    "searchForm": "writable",
    "searchQueryInput": "writable",
    "renderMetadataDisplay": "writable",
    "logInterval": "writable",
    "fetchLogs": "writable",
    "refreshDownloadsInfo": "writable",
    "loadComicsDefaults": "writable",
    "initContinuousModeSettings": "writable",
    "loadUserList": "writable",
    "refreshDeviceList": "writable",
    "refreshUsersList": "writable",
    "clearDownloadsBtn": "writable",
    "clearOfflineData": "writable",
    "forceStorageCleanup": "writable",
    "metadataForm": "writable",
    "saveStatusDiv": "writable",
    "setComicSummary": "writable",
    "onFullscreenReset": "writable",
    "applyFullscreenFitMode": "writable",
    "filterButtonsDiv": "writable",
    "showLatestAddedSmartList": "writable",
    "showLatestConvertedSmartList": "writable",
    "showDownloadedSmartList": "writable",
    "smartListBackBtn": "writable",
    "librarySearchForm": "writable",
    "librarySearchQuery": "writable",
    "librarySearchField": "writable",
    "showSearchView": "writable",
    "clearSearchBtn": "writable",
    "publisherListContainer": "writable",
    "getAllDownloadedComics": "writable",
    "submitButton": "writable",
    "db": "writable",
    "downloadQueue": "writable",
    "saveProgressToDB": "writable",
    "prevBtn": "writable",
    "nextBtn": "writable",
    "updateDownloadedComicProgressData": "writable",
    "renderDownloadedSmartList": "writable",
    "fetchLibraryFromServer": "writable",
    "saveStatusToDB": "writable",
    "updateLibraryProgress": "writable",
    "settingsTabDevices": "writable",
    "openSettingsModal": "readonly",
    "closeSettingsModal": "readonly",
    "handleLogout": "readonly",
    "ctSaveBtn": "readonly",
    "ctConfirmNo": "readonly"
};


export default [
  {
    // Global ignores for all configurations
    ignores: ["public/jszip.min.js"],
  },
  {
    // Base configuration for all JavaScript files
    files: ["**/*.js"],
    ...js.configs.recommended,
    languageOptions: {
      sourceType: "commonjs",
      ecmaVersion: "latest",
    },
  },
  {
    // Jest test files configuration
    files: ["**/*.test.js", "jest.setup.js"],
    languageOptions: {
      globals: {
        ...globals.jest,
        ...globals.node,
      },
    },
  },
  {
    // Server-specific configuration
    files: ["server/**/*.js", "eslint.config.mjs", "server.js", "jest.setup.js"],
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
  },
  {
    // Service worker configuration
    files: ["public/service-worker.js"],
    languageOptions: {
      globals: {
        ...globals.serviceworker,
      },
    },
  },
  {
    // Frontend-specific configuration
    files: ["public/**/*.js"],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...customGlobals,
      },
    },
  }
];
